# Logstash configuration for SentinelFS AI
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Memory settings
pipeline.jvm.heap: 256m

# Dead letter queue
dead_letter_queue.enable: true
path.dead_letter_queue: /usr/share/logstash/dead_letter_queue

# Monitoring
xpack.monitoring.enabled: false

# Security (disabled for development)
xpack.security.enabled: false