# Prometheus Configuration for SentinelZer0
# Auto-discovery and monitoring setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sentinelzer0'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # SentinelZer0 API metrics
  - job_name: 'sentinelzer0-api'
    static_configs:
      - targets: ['sentinelzer0:9090']
        labels:
          service: 'api'
          component: 'inference'
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'monitoring'
          component: 'prometheus'
  
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'cache'
          component: 'redis'
  
  # Node exporter (if using)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'infrastructure'
          component: 'node'
  
  # GPU metrics (if using NVIDIA GPUs with DCGM)
  - job_name: 'gpu'
    static_configs:
      - targets: ['dcgm-exporter:9400']
        labels:
          service: 'infrastructure'
          component: 'gpu'
